### ISSUE TITLE
Why? 

### ISSUE THREAD

**Issue by erfjab** [iamTheNoBody/Aiogram-Persian#1]
Why don't you continue?

**Comment by iamTheNoBody** [comment]
او ، شرمنده رفیق ولی زمان کافی ندارم ولی اگه دوس داشتی یادش بگیری توی گروه ایوگرام فارسی جوینشو این pull که زدیو دیدم ، فک کنم باید براش کمی وقت کنار بزارم :)) چشم یه بخششو کم کم میزارم

**Comment by erfjab** [comment]
یکم برو جلو، باقیشو دوستان حمایت میکنن. هرکی ده جمله بنویسه تموم میشه. دمت گرم ❤️
